export const IRON_SESSION = {
    IRON_SESSION_PASSWORD: process.env
        .NEXT_PUBLIC_IRON_SESSION_PASSWORD as string,

    IRON_SESSION_COOKIE_NAME: process.env
        .NEXT_PUBLIC_IRON_SESSION_COOKIE_NAME as string,

    IRON_SESSION_COOKIE_OPTIONS_HTTP_ONLY:
        process.env.NEXT_PUBLIC_IRON_SESSION_COOKIE_OPTIONS_HTTP_ONLY,

    IRON_SESSION_COOKIE_OPTIONS_SECURE:
        process.env.NEXT_PUBLIC_IRON_SESSION_COOKIE_OPTIONS_SECURE,
};
